    server.modules = (
        "mod_access",
        "mod_accesslog",
        "mod_fastcgi",
        "mod_openssl"  
    )

    server.document-root = "/mynand/web/html"
    # HTTP 监听（可选，可同时监听 HTTP 和 HTTPS）
    server.port = 80        # HTTP 默认端口
    server.bind = "0.0.0.0"

    # HTTPS 监听
    # $SERVER["socket"] == ":443" {   # 选择 HTTPS 默认端口
    #     ssl.engine = "enable"
    #     # ssl.pemfile = "/etc/ssl/web/server.pem"   # 合并的证书+私钥文件
    #     # 如果证书和私钥分开，使用下面两行
    #     ssl.pemfile = "/etc/ssl/web/cert.pem"
    #     ssl.privkey = "/etc/ssl/web/privkey.pem"
    #     # 可选：指定 CA 证书链
    #     # ssl.ca-file = "/etc/ssl/web/ca.pem"
    #     ssl.use-sslv2 = "disable"
    #     ssl.use-sslv3 = "disable"
    #     ssl.cipher-list = "HIGH"
    # }

    server.errorlog = "/mynand/web/logs/error.log"
#    accesslog.filename = "/mynand/web/logs/access.log" //不保留请求日志

    server.pid-file = "/mynand/web/lighttpd.pid"

    server.max-fds = 1024
    server.max-connections = 256
    server.max-request-size = 104857600

    server.upload-dirs = ( "/mynand/web/tmp" )

    index-file.names = ( "index.html" )

    mimetype.assign = (
        ".html" => "text/html",
        ".css"  => "text/css",
        ".js"   => "application/javascript",
        ".png"  => "image/png",
        ".jpg"  => "image/jpeg",
        ".gif"  => "image/gif",
        ".json" => "application/json"
    )

    static-file.exclude-extensions = ( ".fcgi" )

    fastcgi.server = (
        ".fcgi" => (
            "emu2000" => (
                "socket" => "/mynand/web/tmp/fastcgi.sock",
                "bin-path" => "/mynand/web/cgi-bin/web_EMU2000.fcgi",
                "max-procs" => 1,
                "check-local" => "disable",
                "bin-environment" => (
                    "LD_LIBRARY_PATH" => "/mynand/web/lib"
                )
            )
        )
    )
