# process manager config file
###############################################################################
#
# procxx=进程描述,执行文件,进程类型,启动模式,等待时间,串口个数
#   进程类型: 0=普通进程 1=重要进程 2=关键进程
# paraxx=进程启动参数
#
###############################################################################
#[system]
environ=

#[process]
proc01=RTDB Manager,/mynand/bin/rtdbserver,2,1,3
para01=/mynand/config
proc02=gather,/mynand/bin/gather,1,1,5,16
proc03=iec61850,/mynand/bin/iec61850,1,1,3,16
proc04=ntpclient,/mynand/bin/ntpclient,1,1,1,16
proc05=keymonitor,/mynand/bin/keymonitor,1,1,1,16
